---
title: "Beta - Versão Final"
output: html_notebook
---

## Pacotes e Bibliotecas

```{r message=FALSE, warning=FALSE}
library(BETS) # importar a selic
library(zoo) # manupulacao de dados
library(quantmod) # importar os precos do yahoo
library(tidyverse) # manupulacao de dados
```

## Configuracoes

```{r warning=FALSE}
remove(list=ls())
ls()
options(scipen=999)
options(max.print = 100000)
```
## Parametros

```{r}
codigos <- c("CPLE6.SA","TAEE3.SA","CMIG4.SA","EQTL3.SA","ENBR3.SA")
data.inicial <- "2021-01-01"
data.final <- "2021-10-05"
```

## Download dos precos

```{r warning=FALSE}
# objetos que irao receber os precos
ativos <- list()
precosTemp <- NULL

# Laco de repeticao, roda esse bloco de codigo de acordo com o tamanho da carteira
i <- 1
while(i <= length(codigos)) {
  precosTemp  <- na.omit(get.hist.quote(codigos[i], quote = "Close", start = data.inicial, end = data.final))
  ativos[[codigos[i]]] <- precosTemp
  i <- i + 1
  cat("importando os preços do cod.:", codigos[i])
}


# download ibovespa

ibov  <- na.omit(get.hist.quote("^BVSP", quote = "Close", start = data.inicial, end = data.final))

# download selic
Selic.hist <- na.omit(BETSget(11, from = data.inicial, to = data.final))
selic <- zoo(Selic.hist$value)
index(selic) <- Selic.hist$date

precos = as.data.frame(ativos)
names(precos) <- codigos

# excluido os objetos que não serão mais ultilizados
rm(Selic.hist, i, precosTemp, ativos)
```

## Retornos

```{r}
# data frame com os precos e o ibovespa
df.precos <- na.omit(merge(ibov, as.zoo(precos)))
names(df.precos) <- c("ibov", codigos)

# função que calcula os retornos
retorno = function(x){(diff(log(x)))*100}

# retornos de todas as colunas
df.retornos <- as.data.frame(lapply(df.precos, retorno))

# retornos e selic
df.retornos.selic <- as.data.frame(na.omit(merge(as.zoo(df.retornos), selic)))


selic <- data.frame(selic = df.retornos.selic$selic)
row.names(selic) <- row.names(df.retornos.selic)

# excluido os objetos que não serão mais ultilizados
rm(Selic, ibov, precos)
```
## Funcao para calcular o Beta

```{r}
nomes.colunas <- names(df.retornos)

# função beta
calcular_beta <- function(dados, i) {
  
  # objetos temporarios
  betas <- NULL
  interceptos <- NULL
  r2.ajustado <- NULL
  
  r2 <- function(x) {
  r2.temp <- summary(x)
  return(r2.temp$adj.r.squared)
  }
  
  empresa <- nomes.colunas[i]
  ret.excedente <- dados - dados$selic
  
  ret.excedente['selic'] <- NULL

  reg.temp <- lm(ret.excedente[[empresa]]~ret.excedente$ibov)
    
  betas[empresa] <- reg.temp$coef[2]
  interceptos[empresa] <- reg.temp$coef[1]
  
  # R2 - Medida da qualidade da regressão

  r2.ajustado[empresa] <- r2(reg.temp)

  return(list(Betas = betas, Intercepto = interceptos, R2 = r2.ajustado))
}
```

## N Periodos

```{r warning=FALSE}
periodos <- seq(15,150,15)
qtd.cods <- seq(2,length(nomes.colunas),1)
Betas <- NULL
Interceptos <- NULL
R2s <- NULL

# objetos temporarios
df.retornos.temp <- NULL
beta <- NULL
interc  <- NULL
r2 <- NULL

for (p in periodos){
  df.retornos.temp <- tail(df.retornos.selic, p)
    for (c in qtd.cods){
    resultado.temp <- calcular_beta(df.retornos.temp, c)
    
    betas.temp <- resultado.temp$Betas
    beta[c] <- betas.temp
    
    interc.temp <- resultado.temp$Intercepto
    interc[c] <- interc.temp
    
    r2.temp <- resultado.temp$R2
    r2[c] <- r2.temp
    
    }
  
  Betas <- rbind(Betas, beta)
  Interceptos <- rbind(Interceptos, interc)
  R2s <- rbind(R2s, r2)
  
  Betas <- as.data.frame(Betas)
  Interceptos <- as.data.frame(Interceptos)
  R2s <- as.data.frame(R2s)
}

row.names(Betas) <- periodos
row.names(Interceptos) <- periodos
row.names(R2s) <- periodos

names(Betas) <- names(df.retornos)
names(Interceptos) <- names(df.retornos)
names(R2s) <- names(df.retornos)

Betas$ibov <- NULL
Interceptos$ibov <- NULL
R2s$ibov <- NULL

rm(df.retornos.temp,beta,interc,r2,p, c, betas.temp, interc.temp, r2.temp,qtd.cods, resultado.temp)
```

```{r}
print(Betas)
```


```{r warning=FALSE}
Interceptos
```


```{r warning=FALSE}
R2s
```
