---
title: "Notas de Estudos - Gestão de Risco"
output: html_notebook
---

```{r warning=FALSE}
library(tseries)
library(BETS)
library(zoo)
```

```{r}
remove(list=ls())
```


```{r}
codigos <- c("JHSF3.SA","MGLU3.SA")
data.inicial <- "2021-01-01"
data.final <- "2021-11-29"
```


```{r warning=FALSE}
ativo1 <- na.omit(get.hist.quote(codigos[1], quote = "Close", start = data.inicial, end = data.final))

ativo2 <- na.omit(get.hist.quote(codigos[2], quote = "Close", start = data.inicial, end = data.final))

ibov <- na.omit(get.hist.quote("^BVSP", quote = "Close", start = data.inicial, end = data.final))

Selic <- na.omit(BETSget(11, from = data.inicial, to = data.final))
selic <- zoo(Selic$value)
index(selic) <- Selic$date

length(ibov)
length(ativo1)
length(selic)
```

```{r}
df.precos <- na.omit(merge(ibov, selic, ativo1, ativo2))
names(df.precos) <- c("ibov", "selic", codigos)

R.ibov <- diff(log(df.precos$ibov))
R.selic <- diff(log(df.precos$selic))
R.ativo1 <- diff(log(df.precos[,3]))
R.ativo2 <- diff(log(df.precos[,4]))

df.retornos <- na.omit(merge(R.ibov, R.selic, R.ativo1, R.ativo2))
```

```{r}
# Periodo

```


```{r warning=FALSE}
# Gráficos
df.retornos.acum <- cumsum(df.retornos)
names(df.retornos.acum) <- c("Ibovespa", "Selic", codigos)

df.graf <- df.retornos.acum
df.graf$Selic <- NULL

plot(df.graf[,1], 
     main="Comparação entre os ativos",
     ylab="",
     type="l",
     col="black",
     ylim = c(min(df.graf),max(df.graf)))

lines(df.graf[,2], col="red")

lines(df.graf[,3], col="green")

legend("topleft",
     c("IBOVESPA", codigos),
       fill=c("blue","red","green")
)
```

```{r}
RExc.ibov <- df.retornos$R.ibov - df.retornos$R.selic
RExc.ativo1 <- df.retornos$R.ativo1 - df.retornos$R.selic
RExc.ativo2 <- df.retornos$R.ativo2 - df.retornos$R.selic
```

```{r}
# Beta - inclinação da regressão

reg.ativo1 <- lm(RExc.ativo1 ~ RExc.ibov)
reg.ativo2 <- lm(RExc.ativo2 ~ RExc.ibov)

beta.ativos <- c(reg.ativo1$coef[2], reg.ativo2$coef[2])
names(beta.ativos) <- codigos
beta.ativos 
```
```{r}
# Rf(1-Beta) - Ponto de interceptação da regressão

intercept.ativos <- c(reg.ativo1$coef[1], reg.ativo2$coef[1])

names(intercept.ativos) <- codigos

intercept.ativos
```
```{r}
# R2 - Medida da qualidade da regressão

r2 <- function(x) {
  r2.temp <- summary(x)
  return(r2.temp$adj.r.squared)
}

r2.ativos <- c(r2(reg.ativo1), r2(reg.ativo2))

names(r2.ativos) <- codigos

r2.ativos
```

```{r}
#rm(R.ibov,R.selic, R.ativo1, R.ativo2, ibov, selic, ativo1, ativo2)
```

